### ISSUE TITLE
annonsbilderna visas inte

### ISSUE THREAD

**Issue by svnoak** [svnoak/PFW21#121]
Annonsbilderna dyker inte upp, de verkar inte kunna hittas.

**Comment by melsowole** [comment]
När jag öppnar sidan genom live server så fungerar det inte, och det läggs till en random bokstavssekvens i slutet av taggen som gör så att den inte känns igenom som en bild? När jag öppnar filen direkt från datorn så fungerar det som det ska

**Comment by svnoak** [comment]
Skumt. Jag laddar upp dem på servern och kollar om felet finns där också, så får vi kanske acceptera att det är en bugg med Visual Studio Code Live Server.

**Comment by svnoak** [comment]
Samma fel uppstår även på serven, se www.orchid.siebeneicher.se
Här laddas även de andra bilderna inte, så vi får kolla på det.

**Comment by svnoak** [comment]
Kan vara samma anledning som #140
