### ISSUE TITLE
Söker man på "bajs" eller annat så visas alla utbildningar

### ISSUE THREAD

**Issue by Isak-gerre** [svnoak/PFW21#145]

**Comment by svnoak** [comment]
Är nog en del av filterkaskaden, för när den inte hittar något som är inkluderat så skickar den väll bara vidare arrayn och så kommer hela arrayen ut i slutet. Varför exakt vet jag dock inte.

**Comment by Isak-gerre** [comment]
Har vi löst denna? För nu hittar jag ingen bug

**Comment by svnoak** [comment]
Jag har gjort så att om det inte finns något ord i allFilterWords och ingen av de andra filtrena är igång heller så visar den inga resultat. Så det kanske löste det samtidigt

**Comment by svnoak** [comment]
Seems to be solved by #164
