### ISSUE TITLE
Spara sökord under sökbaren som "piller"

### ISSUE THREAD

**Issue by svnoak** [svnoak/PFW21#18]
saveSearchWord("input.value") :: DOM-element, pushar in input.value i searchWords[] och skapar DOM-element av input. 
    DOM-elementet skickas till render.

**Comment by svnoak** [comment]
@Isak-gerre Vill du skriva här mer specifikt vad det är du behöver hjälp med? :) (Och kanske klistra in de kodbitar som det är du funderar över)

**Comment by svnoak** [comment]
Är denna fortfarande aktuell? @Isak-gerre

**Comment by Isak-gerre** [comment]
När den är stresstestad och sånt så är den klar

**Comment by matildaein** [comment]
När jag söker på vissa städer/länder så får jag ändå bara upp program i Spanien. Exempelvis fungerar inte Malmö eller Sverige.
