### ISSUE TITLE
Hur gör jag så att man kan filtrera på rätt sätt

### ISSUE THREAD

**Issue by Isak-gerre** [svnoak/PFW21#48]
Just nu så funkar search.js så att den filtrerar efter sökorden tillsammans. D.v.s. att den tar bort alla program som inte stämmer överens men alla sökord. Då kan man inte skriva in två sökord som hör till programnamnen.

"Law", "Madrid", "Spain" - funkar

"Law, "Medicin", "Design" - funkar inte

Hur ska man göra så man kan skriva "Law", "Medicine", "Spain", "Madrid" så att man får ut rätt sökresultat

**Comment by svnoak** [comment]
Kan man göra någit med include()?

**Comment by Isak-gerre** [comment]
Jag har include på typ 711 ställen ;(

**Comment by Isak-gerre** [comment]
Just nu satsar jag på att lägga in pillerna i kategorier och filtrera dem utifrån en viss hieraki

**Comment by Isak-gerre** [comment]
Har gjort om allt för 11 gången men nu ser det ut som det funkar. Kan finnas ett par buggar kanske. Någon får jättegärna dubbelkolla

**Comment by Isak-gerre** [comment]
EDIT: det finns buggar
